#!/usr/bin/env bash
# Installing nginx web server

# This updates and install nginx
apt-get update -y
apt-get install nginx -y

# This create an HTML file that containing "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# This will check if Nginx is not already running
if [ ! -f /var/run/nginx.pid ]; then
    # Start Nginx
    /usr/sbin/nginx
fi

# This checks Nginx if listening on port 80
if ! netstat -tuln | grep ":80 " > /dev/null; then
    echo "Nginx is not listening on port 80."
    exit 1
fi

# This test Nginx root page
response=$(curl -s http://localhost)
if [[ $response == *"Hello World!"* ]]; then
    echo "Nginx is correctly configured and serving 'Hello World!' at the root."
else
    echo "Nginx is not serving 'Hello World!' at the root. Please check the configuration."
fi
