#!/usr/bin/env bash
# A script that displays Best School 10 times and hi after the 9th using while and if

r=1

while [ $r -le 10 ]
do
    echo "Best School"
    if [ $r -eq 9 ]
    then
        echo "Hi"
    fi
    ((r++))
done
