#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 
r=1
while [ $r -le 20 ]
do
    case $r in
        4)
            echo "4"
            echo "bad luck from China"
            ;;
        9)
            echo "9"
            echo "bad luck from Japan"
            ;;
        17)
            echo "17"
            echo "bad luck from Italy"
            ;;
        *)
            echo $r
            ;;
    esac

    ((r++))
done
