#!/bin/bash/env bash


# Specify the server IP address or hostname
server_ip="8.8.8.8"

# Path to the private key file
private_key_path="~/.ssh/school"

# SSH command with single-character flags
ssh -i "$private_key_path" ubuntu@$server_ip
